### PR TITLE
refactor: removed unused code

### PR DESCRIPTION
**Pull request by KunalSin9h**

### CODE REVIEW

**Comment by jclulow** [comment]
Thanks, but I believe this code is actually used!  Cheers.

**Comment by KunalSin9h** [comment]
@jclulow may you please explain how this code works and how it is being used.

**Comment by david-crespo** [comment]
It is mutating `app.inner`.

https://github.com/oxidecomputer/clock/blob/5868dff3a1a965a403bb4754750fd4fb91b784f6/src/main.rs#L241-L249

It's in a block so that the lock is released when `i` goes out of scope.

https://github.com/oxidecomputer/clock/blob/5868dff3a1a965a403bb4754750fd4fb91b784f6/src/main.rs#L318-L322

**Comment by KunalSin9h** [comment]
got it, to mutate a `mutex` we need to get a `mutable` reference (`mut`) that why `i` is that reference.
thanks @david-crespo .

**Pull request closed without merging**
